# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20160213_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Content',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Image',
        ),
    ]
